--- 
graphic: 
  fonts: 
    font_pack: assets/fonts/default
    wombo_font: broken_15.ttf
  textures: 
    item_background: crate.png
    items: 
      Aubergine: item4.png
      Banana: item5.png
      Carrot: item1.png
      Mushroom: item3.png
      Strawberry: item2.png
      Watermelon: item6.png
    texture_pack: assets/graphics/default
    window_background: grass.png
  window: 
    size: 
      - 1280
      - 720
